apiVersion: v1
kind: Service
metadata:
  name: chat-agent2-service
spec:
  selector:                  
    deploymentconfig: chat-agent2-deployment
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
