apiVersion: v1
kind: Service
metadata:
  name: chat-agent1-service
spec:
  selector:                  
    deploymentconfig: chat-agent1-deployment
  ports:
  - name: 8080-tcp
    port: 8080               
    protocol: TCP
    targetPort: 8080
