apiVersion: v1
kind: Pod
metadata:
  name: chat-agent1-pod
spec:
  containers:
    - env:
      name: spring-app-1
      image: avikulin/simple-chat-agent:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
